apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-haven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mss-haven
  template:
    metadata:
      labels:
        app: mss-haven
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: mss-user
        image: mss-user:latest
        ports:
          - containerPort: 3000
            targetPort: http
      - name: mss-haven
        image: mss-haven:latest
        ports:
          - containerPort: 4000
            targetPort: http
      - name: mss-authenticate
        image: mss-haven:latest
        ports:
          - containerPort: 5000
            targetPort: http 

---
apiVersion: v1
kind: Service
metadata:
  name: mss-haven-service
spec:
  selector:
    app: mss-haven
  ports:
    - port: 80
      targetPort: http